name: Deploy Arithmetic Calculator UI

on:
  repository_dispatch:
    types: [deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout React Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install and Build React Application
        run: |
          npm install
          npm run build

      - name: Deploy React Application
        run: |
          npm start &
        